# Generated by Django 6.0.2 on 2026-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Untitled Submission', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('code', 'Code File'), ('document', 'Document'), ('image', 'Image'), ('zip', 'ZIP File'), ('github', 'GitHub Repository')], max_length=20),
        ),
    ]
