# Generated by Django 6.0.2 on 2026-03-28 23:05

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_zip_file_submission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/files/', validators=[submissions.models.validate_file_extension, submissions.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/', validators=[submissions.models.validate_file_size]),
        ),
    ]
